# Generated by Django 5.1 on 2024-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myMember',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_birth', models.DateField()),
                ('user_avator', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
