# Generated by Django 5.1 on 2024-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_avatar', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
